=== navaneeth-ashok/SupportTicketingSystem/App_Data/users.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="userID" type="xs:positiveInteger" />
                            <xs:element name="userName">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="firstName" type="xs:string" />
                                        <xs:element name="middleName" type="xs:string" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="lastName" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="userEmail" type="emailAddress" />
                            <xs:element name="userPasswordHash" type="xs:string" />
                            <xs:element name="department" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="type" type="userType" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="emailAddress">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^\.]+\..+" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="userType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="[Admin][admin]" />
            <xs:enumeration value="[Support][support]" />
            <xs:enumeration value="[Client][client]" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== navaneeth-ashok/SupportTicketingSystem/App_Data/users.xml
<?xml version="1.0" encoding="utf-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
  <!--type = admin/client/guest-->
  <user type="admin">
    <userID>100001</userID>
    <!-- middlename :optional -->
    <userName>
      <firstName>John</firstName>
      <lastName>Doe</lastName>
    </userName>
    <!-- credentials -->
    <userEmail>johndoe@something.com</userEmail>
    <userPasswordHash>jnfgkjnjfbqawDBhabdh</userPasswordHash>
    <!-- user dept -->
    <department>Support</department>
  </user>
  <user type="client">
    <userID>200001</userID>
    <userName>
      <firstName>Spi</firstName>
      <middleName>Der</middleName>
      <lastName>Man</lastName>
    </userName>
    <userEmail>spiderman@avengers.com</userEmail>
    <userPasswordHash>hsdasbDHausgd6%#^RT</userPasswordHash>
    <department>Engineering</department>
  </user>
  <user type="admin">
    <userID>200002</userID>
    <userName>
      <firstName>Navaneeth</firstName>
      <middleName>
      </middleName>
      <lastName>Ashok</lastName>
    </userName>
    <userEmail>navaneeth619@gmail.com</userEmail>
    <userPasswordHash>AQAAAAEAACcQAAAAEAgtNKBszsJmflE4oyO+fOpyRA3lY+OxyCOvDv97nzHhX08/2GAoyN5jef1+0AihYA==</userPasswordHash>
    <department>support</department>
  </user>
  <user type="Admin">
    <userID>200003</userID>
    <userName>
      <firstName>Navaneeth</firstName>
      <middleName>
      </middleName>
      <lastName>Ashok</lastName>
    </userName>
    <userEmail>navaneeth619@gmail.com</userEmail>
    <userPasswordHash>AQAAAAEAACcQAAAAEAgtNKBszsJmflE4oyO+fOpyRA3lY+OxyCOvDv97nzHhX08/2GAoyN5jef1+0AihYA==</userPasswordHash>
    <department>TechSupport</department>
  </user>
  <user type="Admin">
    <userID>200004</userID>
    <userName>
      <firstName>Bat</firstName>
      <middleName>Ter</middleName>
      <lastName>Man</lastName>
    </userName>
    <userEmail>something@test.com</userEmail>
    <userPasswordHash>abcdefghi</userPasswordHash>
    <department>Engg</department>
  </user>
  <user type="Admin">
    <userID>200005</userID>
    <userName>
      <firstName>Navaneeth</firstName>
      <middleName>
      </middleName>
      <lastName>Ashok</lastName>
    </userName>
    <userEmail>asbdhasdvhadvh@asbdh.com</userEmail>
    <userPasswordHash>hasbdvgavdhasbdabd</userPasswordHash>
    <department>Engg</department>
  </user>
</users>
